version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: speedhorizon-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

  app:
    build: .
    container_name: speedhorizon-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://kubra32nur:kubra32kubra@ac-w5zd64r-shard-00-00.ijfvnnc.mongodb.net:27017,ac-w5zd64r-shard-00-01.ijfvnnc.mongodb.net:27017,ac-w5zd64r-shard-00-02.ijfvnnc.mongodb.net:27017/?ssl=true&replicaSet=atlas-4y348o-shard-0&authSource=admin&retryWrites=true&w=majority&appName=speedhorizon
      - PORT=5001
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - rabbitmq 